networks:
  piq-dev:
    driver: bridge

services:
  piq-service:
    container_name: piq-service
    image: piq-service
    build:
      context: .
      dockerfile: PIQService/PIQService.Api/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONTAINER: "piq-db"
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - piq-db
  
  account-service:
    container_name: account-service
    image: piq-account-service
    build:
      context: .
      dockerfile: AccountService/AccountService/Dockerfile
    restart: always
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONTAINER: "piq-db"
    env_file:
      - .env
    ports:
      - "5247:5247"
    depends_on:
      - piq-db
  
  piq-db:
    container_name: piq-db
    image: mysql:9.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: