networks:
  piq-dev:
    driver: bridge

services:
  piq-account-service:
    image: piq-account-service
    build:
      context: .
      dockerfile: AccountService/AccountService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONTAINER: "piq-db"
    env_file:
      - .env
    depends_on:
      - piq-db
  
  piq-db:
    container_name: piq-db
    image: mysql:9.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: